// 献立データベース
// temp: 気温帯 ['cold'(〜15℃) / 'mild'(15〜25℃) / 'hot'(25℃〜)]
// rainOk: 雨の日向き（手間少なめ・室内で完結・温かい）
// effort: 手間 1(楽)〜3(手間)
// stamina: スタミナ度 1〜3（育ち盛り・運動する子向け）
// kid: 子供に人気
// spicy: 辛い（子供には甘口対応の注記に使用）
// allergens: 主なアレルゲン（除外フィルタ用）
// ingredients: 主な買い物リスト用材料

const MENUS = [
  // ── 寒い日（鍋・煮込み・温かい） ───────────────────────────
  { id: 1, name: "鶏の寄せ鍋", items: ["鶏もも肉の寄せ鍋", "白菜・きのこ・豆腐", "〆のうどん or 雑炊"],
    temp: ["cold"], rainOk: true, effort: 1, stamina: 2, kid: true, spicy: false,
    allergens: ["小麦"], ingredients: ["鶏もも肉", "白菜", "しめじ", "豆腐", "長ねぎ", "うどん", "だし"] },
  { id: 2, name: "ビーフシチュー", items: ["ビーフシチュー", "バターロール", "グリーンサラダ"],
    temp: ["cold"], rainOk: true, effort: 3, stamina: 3, kid: true, spicy: false,
    allergens: ["小麦", "乳"], ingredients: ["牛肉(角切り)", "じゃがいも", "にんじん", "玉ねぎ", "デミグラスルウ", "バターロール"] },
  { id: 3, name: "クリームシチュー", items: ["チキンクリームシチュー", "ごはん or バゲット", "ブロッコリー"],
    temp: ["cold"], rainOk: true, effort: 2, stamina: 2, kid: true, spicy: false,
    allergens: ["小麦", "乳"], ingredients: ["鶏もも肉", "じゃがいも", "にんじん", "玉ねぎ", "ブロッコリー", "牛乳", "シチュールウ"] },
  { id: 4, name: "カレーライス", items: ["ポークカレー", "福神漬け", "コールスロー"],
    temp: ["cold", "mild"], rainOk: true, effort: 2, stamina: 3, kid: true, spicy: false,
    allergens: ["小麦"], ingredients: ["豚こま肉", "じゃがいも", "にんじん", "玉ねぎ", "カレールウ", "米"] },
  { id: 5, name: "豚汁定食", items: ["鮭の塩焼き", "具だくさん豚汁", "ごはん・小鉢"],
    temp: ["cold"], rainOk: true, effort: 2, stamina: 2, kid: true, spicy: false,
    allergens: [], ingredients: ["生鮭", "豚こま肉", "大根", "にんじん", "ごぼう", "こんにゃく", "味噌", "米"] },
  { id: 6, name: "すき焼き", items: ["牛すき焼き", "溶き卵", "ごはん"],
    temp: ["cold"], rainOk: true, effort: 2, stamina: 3, kid: true, spicy: false,
    allergens: ["卵", "小麦"], ingredients: ["牛薄切り肉", "白菜", "長ねぎ", "焼き豆腐", "しらたき", "春菊", "卵", "割り下"] },
  { id: 7, name: "マカロニグラタン", items: ["海老とマカロニのグラタン", "コーンスープ", "サラダ"],
    temp: ["cold"], rainOk: true, effort: 3, stamina: 2, kid: true, spicy: false,
    allergens: ["小麦", "乳", "えび"], ingredients: ["えび", "マカロニ", "玉ねぎ", "牛乳", "バター", "チーズ", "コーンスープ"] },
  { id: 8, name: "肉じゃが定食", items: ["肉じゃが", "焼き魚(さば)", "ごはん・味噌汁"],
    temp: ["cold", "mild"], rainOk: true, effort: 2, stamina: 2, kid: true, spicy: false,
    allergens: [], ingredients: ["豚こま肉", "じゃがいも", "にんじん", "玉ねぎ", "さば", "味噌", "米"] },
  { id: 9, name: "おでん", items: ["おでん盛り合わせ", "からし", "ごはん"],
    temp: ["cold"], rainOk: true, effort: 2, stamina: 1, kid: true, spicy: false,
    allergens: ["小麦", "卵"], ingredients: ["大根", "卵", "ちくわ", "こんにゃく", "はんぺん", "がんもどき", "おでんの素"] },
  { id: 10, name: "麻婆豆腐(甘口)", items: ["麻婆豆腐", "中華スープ", "ごはん"],
    temp: ["cold", "mild"], rainOk: true, effort: 1, stamina: 2, kid: true, spicy: true,
    allergens: ["大豆"], ingredients: ["豚ひき肉", "豆腐", "長ねぎ", "麻婆豆腐の素(甘口)", "米"] },
  { id: 11, name: "ロールキャベツ", items: ["トマトロールキャベツ", "ごはん or パン", "コンソメスープ"],
    temp: ["cold"], rainOk: true, effort: 3, stamina: 2, kid: true, spicy: false,
    allergens: [], ingredients: ["合いびき肉", "キャベツ", "玉ねぎ", "トマト缶", "コンソメ"] },
  { id: 12, name: "けんちんうどん", items: ["けんちんうどん", "ちくわ天", "おにぎり"],
    temp: ["cold"], rainOk: true, effort: 1, stamina: 1, kid: true, spicy: false,
    allergens: ["小麦"], ingredients: ["うどん", "大根", "にんじん", "ごぼう", "里芋", "豆腐", "長ねぎ"] },

  // ── 過ごしやすい日（定番・炒め物・焼き物） ─────────────────
  { id: 20, name: "鶏の唐揚げ定食", items: ["鶏の唐揚げ", "千切りキャベツ・レモン", "ごはん・味噌汁"],
    temp: ["mild", "hot"], rainOk: false, effort: 2, stamina: 3, kid: true, spicy: false,
    allergens: ["小麦"], ingredients: ["鶏もも肉", "にんにく", "しょうが", "片栗粉", "キャベツ", "米"] },
  { id: 21, name: "ハンバーグ", items: ["煮込みハンバーグ", "温野菜", "ごはん・コーンスープ"],
    temp: ["mild", "cold"], rainOk: true, effort: 3, stamina: 3, kid: true, spicy: false,
    allergens: ["卵", "小麦", "乳"], ingredients: ["合いびき肉", "玉ねぎ", "卵", "パン粉", "デミソース", "ブロッコリー", "米"] },
  { id: 22, name: "豚の生姜焼き", items: ["豚の生姜焼き", "千切りキャベツ", "ごはん・味噌汁"],
    temp: ["mild", "cold"], rainOk: true, effort: 1, stamina: 2, kid: true, spicy: false,
    allergens: [], ingredients: ["豚ロース", "玉ねぎ", "しょうが", "キャベツ", "米"] },
  { id: 23, name: "焼き餃子", items: ["焼き餃子(たっぷり)", "中華スープ", "ごはん"],
    temp: ["mild", "hot"], rainOk: true, effort: 2, stamina: 2, kid: true, spicy: false,
    allergens: ["小麦"], ingredients: ["豚ひき肉", "キャベツ", "にら", "餃子の皮", "にんにく", "米"] },
  { id: 24, name: "親子丼", items: ["親子丼", "味噌汁", "浅漬け"],
    temp: ["mild", "cold"], rainOk: true, effort: 1, stamina: 2, kid: true, spicy: false,
    allergens: ["卵"], ingredients: ["鶏もも肉", "卵", "玉ねぎ", "三つ葉", "米", "めんつゆ"] },
  { id: 25, name: "オムライス", items: ["ふわとろオムライス", "コンソメスープ", "サラダ"],
    temp: ["mild"], rainOk: true, effort: 2, stamina: 2, kid: true, spicy: false,
    allergens: ["卵"], ingredients: ["鶏もも肉", "卵", "玉ねぎ", "ケチャップ", "米", "ピーマン"] },
  { id: 26, name: "鮭のホイル焼き", items: ["鮭ときのこのホイル焼き", "ごはん", "けんちん汁"],
    temp: ["mild", "cold"], rainOk: true, effort: 2, stamina: 1, kid: true, spicy: false,
    allergens: ["乳"], ingredients: ["生鮭", "しめじ", "玉ねぎ", "バター", "レモン", "米"] },
  { id: 27, name: "回鍋肉", items: ["回鍋肉", "わかめスープ", "ごはん"],
    temp: ["mild", "hot"], rainOk: true, effort: 1, stamina: 2, kid: true, spicy: true,
    allergens: ["大豆"], ingredients: ["豚バラ肉", "キャベツ", "ピーマン", "テンメンジャン", "米"] },
  { id: 28, name: "ミートソースパスタ", items: ["ミートソースパスタ", "ガーリックトースト", "サラダ"],
    temp: ["mild"], rainOk: true, effort: 2, stamina: 3, kid: true, spicy: false,
    allergens: ["小麦"], ingredients: ["合いびき肉", "玉ねぎ", "にんじん", "トマト缶", "スパゲッティ", "バゲット"] },
  { id: 29, name: "さばの味噌煮", items: ["さばの味噌煮", "ほうれん草のおひたし", "ごはん・味噌汁"],
    temp: ["mild", "cold"], rainOk: true, effort: 2, stamina: 1, kid: true, spicy: false,
    allergens: [], ingredients: ["さば", "しょうが", "味噌", "ほうれん草", "米"] },
  { id: 30, name: "エビフライ", items: ["エビフライ・タルタル", "ポテトサラダ", "ごはん・スープ"],
    temp: ["mild", "hot"], rainOk: false, effort: 3, stamina: 2, kid: true, spicy: false,
    allergens: ["えび", "卵", "小麦"], ingredients: ["えび", "パン粉", "卵", "じゃがいも", "きゅうり", "米"] },
  { id: 31, name: "牛丼", items: ["牛丼", "味噌汁", "冷奴"],
    temp: ["mild", "hot"], rainOk: true, effort: 1, stamina: 2, kid: true, spicy: false,
    allergens: ["大豆"], ingredients: ["牛薄切り肉", "玉ねぎ", "紅生姜", "豆腐", "米", "めんつゆ"] },
  { id: 32, name: "チキンソテー", items: ["チキンソテーきのこソース", "バターライス", "ミネストローネ"],
    temp: ["mild"], rainOk: true, effort: 2, stamina: 2, kid: true, spicy: false,
    allergens: ["乳"], ingredients: ["鶏もも肉", "しめじ", "玉ねぎ", "トマト缶", "バター", "米"] },

  // ── 暑い日（さっぱり・麺・冷たい） ────────────────────────
  { id: 40, name: "冷やし中華", items: ["冷やし中華(具だくさん)", "餃子", "わかめスープ"],
    temp: ["hot"], rainOk: false, effort: 2, stamina: 2, kid: true, spicy: false,
    allergens: ["小麦", "卵"], ingredients: ["中華麺", "きゅうり", "ハム", "卵", "トマト", "冷やし中華のたれ"] },
  { id: 41, name: "冷しゃぶサラダ", items: ["豚冷しゃぶサラダ", "冷奴", "ごはん・味噌汁"],
    temp: ["hot"], rainOk: false, effort: 1, stamina: 2, kid: true, spicy: false,
    allergens: ["大豆"], ingredients: ["豚しゃぶ肉", "レタス", "きゅうり", "トマト", "豆腐", "ごまだれ", "米"] },
  { id: 42, name: "そうめんと天ぷら", items: ["薬味そうめん", "野菜と海老の天ぷら", "枝豆"],
    temp: ["hot"], rainOk: false, effort: 2, stamina: 1, kid: true, spicy: false,
    allergens: ["小麦", "えび"], ingredients: ["そうめん", "えび", "なす", "かぼちゃ", "みょうが", "めんつゆ", "枝豆"] },
  { id: 43, name: "スタミナ丼", items: ["ねぎ塩豚カルビ丼", "わかめスープ", "冷奴"],
    temp: ["hot", "mild"], rainOk: true, effort: 1, stamina: 3, kid: true, spicy: false,
    allergens: ["大豆"], ingredients: ["豚バラ肉", "長ねぎ", "レモン", "豆腐", "米", "ごま油"] },
  { id: 44, name: "ガパオライス", items: ["ガパオライス(目玉焼きのせ)", "春雨スープ", "きゅうりサラダ"],
    temp: ["hot"], rainOk: true, effort: 2, stamina: 2, kid: true, spicy: true,
    allergens: ["卵"], ingredients: ["鶏ひき肉", "パプリカ", "玉ねぎ", "バジル", "卵", "米", "ナンプラー"] },
  { id: 45, name: "夏野菜カレー", items: ["夏野菜カレー", "らっきょう", "ヨーグルトサラダ"],
    temp: ["hot", "mild"], rainOk: true, effort: 2, stamina: 3, kid: true, spicy: false,
    allergens: ["小麦", "乳"], ingredients: ["鶏もも肉", "なす", "ズッキーニ", "パプリカ", "トマト", "カレールウ", "米"] },
  { id: 46, name: "手巻き寿司", items: ["手巻き寿司", "茶碗蒸し", "お吸い物"],
    temp: ["hot", "mild"], rainOk: true, effort: 2, stamina: 1, kid: true, spicy: false,
    allergens: ["卵"], ingredients: ["刺身盛り合わせ", "きゅうり", "納豆", "卵", "焼きのり", "米", "寿司酢"] },
  { id: 47, name: "おうちたこ焼き", items: ["たこ焼き", "焼きそば", "枝豆"],
    temp: ["hot", "mild"], rainOk: true, effort: 2, stamina: 2, kid: true, spicy: false,
    allergens: ["小麦", "卵"], ingredients: ["たこ", "たこ焼き粉", "卵", "キャベツ", "青ねぎ", "焼きそば麺", "枝豆"] },
  { id: 48, name: "ざるうどんと唐揚げ", items: ["ざるうどん", "鶏の唐揚げ", "冷やしトマト"],
    temp: ["hot"], rainOk: false, effort: 2, stamina: 3, kid: true, spicy: false,
    allergens: ["小麦"], ingredients: ["うどん", "鶏もも肉", "片栗粉", "トマト", "めんつゆ", "薬味ねぎ"] },
];

// UMD 風エクスポート（モジュール未使用でも window から参照可能）
if (typeof module !== "undefined" && module.exports) { module.exports = { MENUS }; }
